### ISSUE TITLE
load_skybox Lua API function is broken

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#119]
share/snis/luascripts/COLLISION.LUA tries to use load_skybox() and this happens in the client:

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./snis_client...done.
[New LWP 20756]
[New LWP 20766]
[New LWP 20765]
[New LWP 20767]
[New LWP 20768]
[New LWP 20778]
[New LWP 20779]
[New LWP 20764]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./snis_client --fullscreen --starship spacenerd --pw spacenerd -j /dev/input/by'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f00cbc98cc0 in _IO_vfprintf_internal (s=s@entry=0x7ffcbedea630, format=<optimized out>, format@entry=0x4d27b0 "solarsystems/%s/%s", ap=ap@entry=0x7ffcbedea758)
    at vfprintf.c:1632
1632	vfprintf.c: No such file or directory.
[Current thread is 1 (Thread 0x7f00ce733a00 (LWP 20756))]
(gdb) bt
#0  0x00007f00cbc98cc0 in _IO_vfprintf_internal (s=s@entry=0x7ffcbedea630, format=<optimized out>, format@entry=0x4d27b0 "solarsystems/%s/%s", ap=ap@entry=0x7ffcbedea758)
    at vfprintf.c:1632
#1  0x00007f00cbcba1cb in __IO_vsprintf (string=0x7ffcbedea850 "solarsystems/default/", format=0x4d27b0 "solarsystems/%s/%s", args=args@entry=0x7ffcbedea758)
    at iovsprintf.c:42
#2  0x00007f00cbc9f9c7 in __sprintf (s=<optimized out>, format=<optimized out>) at sprintf.c:32
#3  0x000000000048fb63 in expire_per_solarsystem_textures (old_solarsystem=0x8ab2a0 <old_solarsystem_name> "default", assets=0x35a7950) at snis_client.c:16802
#4  0x000000000048fd1b in reload_per_solarsystem_textures (old_solarsystem=0x8ab2a0 <old_solarsystem_name> "default", 
    new_solarsystem=0x8ab220 <dynamic_solarsystem_name> "karado", old_assets=0x35a7950, new_assets=0x7f00800011b0) at snis_client.c:16824
#5  0x000000000048f6db in load_per_solarsystem_textures () at snis_client.c:16739
#6  0x000000000048fd59 in load_textures () at snis_client.c:16836
#7  0x000000000048dd23 in main_da_expose (w=0x360b0a0, event=0x7ffcbedecee0, p=0x0) at snis_client.c:16121
#8  0x00007f00ce043afc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#9  0x00007f00cda18fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f00cda2afc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007f00cda337f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f00cda3408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007f00ce15b8cc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#14 0x00007f00ce0427ed in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#15 0x00007f00cdc9db9f in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#16 0x00007f00cdc9a671 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#17 0x00007f00cdc9afa8 in gdk_window_process_all_updates () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#18 0x00007f00cdc9b009 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#19 0x00007f00cdc79d57 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#20 0x00007f00cd74204a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007f00cd7423f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f00cd742712 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f00ce0416a7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x0000000000494961 in main (argc=10, argv=0x7ffcbeded328) at snis_client.c:18404

Pretty sure this is because now there's more than just the skybox, there are a whole bunch of solarsystem specific assets and the lua load_skybox() function didn't get updated when those assets came into being.

May need to drop load_skybox() in its current form and do something more like "load_solarsystem()". Although it does seem like maybe you should be able to load a skybox independently of the rest. In any case, it's currently broken.

**Comment by smcameron** [comment]
Fixed Feb 28, 2018 by 5a80583705178671faff7934f2fdfa1479219f3f
