### ISSUE TITLE
Regenerate script causes a crash with optimized build

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#155]
Doesn't seem to reproduce if you "make mostly-clean; make O=0", but "make mostly-clean; make" reproduces this when you run the regenerate script from the demon screen:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./snis_server -l localhost -L KARADO --enable-enscript -m narnia -s karado'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:90
90	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
[Current thread is 1 (Thread 0x7f1a28bc3700 (LWP 12288))]
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:90
#1  0x0000000000415eab in planetary_atmosphere_profile_new ()
#2  0x000000000041643d in add_random_atmospheres ()
#3  0x0000000000462966 in populate_universe ()
#4  0x00000000004636d8 in l_regenerate_universe ()
#5  0x00007f1a2829c8ed in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#6  0x00007f1a282a84ed in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#7  0x00007f1a2829cc2e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#8  0x00007f1a2829c26f in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#9  0x00007f1a2829ce71 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#10 0x00007f1a28298d91 in lua_pcallk () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
#11 0x000000000040ba99 in main ()
```

**Comment by smcameron** [comment]
Seems to be having trouble re-initializing the atmosphere profiles, and dies on the very last one... there are 100 atmospheres per type, and the TITAN-CLASS is the last type, so it dies on the last one of the last type.

```
add_random_atmospheres, i = 99, name = TITAN-CLASS-99
papn A
papn B
papn D
p = 0x2ff4a70
model = 0x2ff4ba0
p->major_compound = 0x301c3d0
```

It's dying here:

```
189         } else {
190                 p->temperature = model->temperature;
191                 p->pressure = model->pressure;
192                 p->type = model->type;
193                 p->nminor = model->nminor;
194                 p->nmajor = model->nmajor;
195                 p->major_compound = malloc(p->nmajor * sizeof(*p->major_compound));
196                 p->minor_compound = malloc(p->nminor * sizeof(*p->minor_compound));
197                 p->minor_ppm = malloc(p->nminor * sizeof(*p->minor_ppm));
198                 p->major_fraction = malloc(p->nmajor * sizeof(*p->major_fraction));
199                 fprintf(stderr, "papn D\n"); fflush(stderr);
200                 fprintf(stderr, "p = %p\n", p); fflush(stderr);
201                 fprintf(stderr, "model = %p\n", model); fflush(stderr);
202                 fprintf(stderr, "p->major_compound = %p\n", p->major_compound); fflush(stderr);
203                 fprintf(stderr, "model->major_compound = %p\n", model->major_compound); fflush(stderr);
204                 memcpy(p->major_compound, model->major_compound, p->nmajor * sizeof(*p->major_compound)); // <---- dies here
205                 fprintf(stderr, "papn E\n"); fflush(stderr);
206                 memcpy(p->minor_compound, model->minor_compound, p->nminor * sizeof(*p->minor_compound));
207                 fprintf(stderr, "papn F\n"); fflush(stderr);
208                 memcpy(p->minor_ppm, model->minor_ppm, p->nminor * sizeof(*p->minor_ppm));
209                 fprintf(stderr, "papn G\n"); fflush(stderr);
210                 memcpy(p->major_fraction, model->major_fraction, p->nmajor * sizeof(*p->major_fraction));
211                 fprintf(stderr, "papn H\n"); fflush(stderr);
212         }
```

**Comment by smcameron** [comment]
Avoided the problem via 92d08c111702feaefd13ef4b39105db44dce10eb
