### ISSUE TITLE
snis_server crashed when mining bot was chasing a derelict that disappeared

### ISSUE THREAD

**Issue by smcameron** [smcameron/space-nerds-in-space#163]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./snis_server -l localhost -L KARADO --enable-enscript -m narnia -s karado'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043b7e7 in npc_menu_item_mining_bot_status_report ()
[Current thread is 1 (Thread 0x7fe775ffb700 (LWP 1807))]
(gdb) bt
#0  0x000000000043b7e7 in npc_menu_item_mining_bot_status_report ()
#1  0x000000000043c214 in generic_npc_bot ()
#2  0x000000000043cb5b in process_comms_transmission ()
#3  0x000000000047becd in per_client_read_thread ()
#4  0x00007fe77d0e36ba in start_thread (arg=0x7fe775ffb700) at pthread_create.c:333
#5  0x00007fe77ce193dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 

I think maybe the derelict expired and deleted itself while the mining bot was chasing it, then snis_server puked when I asked the mining bot for a status report.

**Comment by smcameron** [comment]
This particular crash should be fixed by 66a42e9e5b623156bedef119171d0476294ef6f7
